version: '3'

services:
  engine:
    container_name: clinical-ner
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "5555:5555"
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
