FROM pytorch/pytorch

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update --allow-insecure-repositories && apt-get install -y pkg-config git make

RUN pip3 install -r requirements.txt

COPY app.py app.py
COPY clinicalner.py clinicalner.py
COPY static/ static/

CMD [ "python3", "app.py"]